In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('Raw Sales Data.csv')
df.head()

,Month,Channel,Sub-Channels,Product Name,Category,Qty,Sales
0,01-Dec-20,Marketplace,AMAZON,ALOE + AMLA JUICE 1 L,Juices,"1,116","4,28,700"
1,01-Dec-20,Marketplace,AMAZON,ALOE + GARCINIA JUICE 1 L,Juices,"3,003","13,74,831"
2,01-Dec-20,Marketplace,AMAZON,ALOE VERA JUICE 1 L,Juices,"2,962","7,32,167"
3,01-Dec-20,Marketplace,AMAZON,ALOE VERA SKIN GEL 500 GM,Gourmet Nutrition,"1,004","3,77,100"
4,01-Dec-20,Marketplace,AMAZON,NEEM JUICE 1 L,Juices,555,"1,52,287"

In [5]:
df['Qty']=df['Qty'].str.replace(',','')
df['Sales']=df['Sales'].str.replace(',','')

In [6]:
df.rename(columns={'Sub-Channels':'Sub_Channels'},inplace=True)
df.columns

Index(['Month', 'Channel', 'Sub_Channels', 'Product Name', 'Category', 'Qty',
       'Sales'],
      dtype='object')

In [7]:
df['Month']= pd.to_datetime(df['Month'])
df[['Qty', 'Sales']] = df[['Qty', 'Sales']].astype(int)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Month         224 non-null    datetime64[ns]
 1   Channel       224 non-null    object
 2   Sub_Channels  224 non-null    object
 3   Product Name  224 non-null    object
 4   Category      224 non-null    object
 5   Qty           224 non-null    int32
 6   Sales         224 non-null    int32
dtypes: datetime64[ns](1), int32(2), object(4)
memory usage: 10.6+ KB

In [8]:
#Question 1)Monthwise number of quantities sold
df_month=df.groupby(df.Month)['Qty'].sum()
df_month

Month
2020-12-01    85427
2021-01-01    67732
2021-02-01    76393
2021-03-01    80229
Name: Qty, dtype: int32

In [9]:
#Question 2) Category wise Qty sold
df_Category=df.groupby(df.Category)['Qty'].sum()
df_Category

Category
Functional nutrition     42354
Gourmet Nutrition        89279
Juices                  178148
Name: Qty, dtype: int32

In [10]:
#Question 3) Sub-channel wise total sales
df_sub_chan=df.groupby(df.Sub_Channels)['Sales'].sum()
df_sub_chan

Sub_Channels
AMAZON               35606804
Big Basket            1207522
D2C                  28047538
Flipkart              3770415
GOQII                  582600
Offline - Central      375332
Offline - East         811146
Offline - MT          6257948
Offline - South       3446395
Offline - West        6441427
Offline -North        1206564
Name: Sales, dtype: int32

In [11]:
#Question 4) Highest sale in which month
df_high_sale=df[["Month","Sales"]][df['Sales']==df["Sales"].max()]
df_high_sale

         Month    Sales
168 2021-03-01  4390500

In [19]:
#Question 5) Highest selling product (based on sales) (packaging quantity doesn't matter Ex. consider "GET SLIM JUICE 1 L" and "GET SLIM JUICE 500 ML" as one product)
df["base_product_name"] = df["Product Name"].str.replace('\d+','1')
df["base_product_name"] = df["base_product_name"].apply(lambda x:x.split('1') [0])
most_sell_product = pd.DataFrame(df.groupby("base_product_name")["Qty"].sum().reset_index())
most_sell_product

C:\Users\akrit\AppData\Local\Temp\ipykernel_21348\2741843569.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["base_product_name"] = df["Product Name"].str.replace('\d+','1')

                  base_product_name    Qty
0                ALOE + AMLA JUICE    5063
1            ALOE + GARCINIA JUICE   23585
2                  ALOE VERA JUICE   28788
3               ALOE VERA SKIN GEL   44890
4               AMLA + GILOY JUICE     502
5                       AMLA JUICE   34378
6               APPLE CIDER VINEGAR  23501
7                   DIA FREE JUICE    4119
8                GET SLIM CAPSULES     715
9                   GET SLIM JUICE   24731
10                    HIMALAYA OIL    8009
11               IMMUNE CARE JUICE    2301
12              KARELA JAMUN JUICE   13023
13    MASALA SUPERGRAIN MIX ENERGY    1560
14  MASALA SUPERGRAIN MIX IMMUNITY    5501
15                      NEEM JUICE    2697
16                      NONI JUICE    8936
17                 ORGANIC GULKAND    2959
18          ORGANIC JAGGERY POWDER   28915
19              RAW HONEY ( MADHU)     971
20          SLIM SHAKE - CHOCOLATE    1338
21              SLIM SHAKE - MANGO    1179
22                  TRIPHALA JUICE    3183
23               TULSI GILOY JUICE   13679
24       VEGAN PROTEIN - CHOCOLATE     551
25                 VIGOR MAX JUICE    1305
26              VIRGIN COCONUT OIL   11544
27               WHEAT GRASS JUICE   11858

In [22]:
 #Question 6)List of different products company is offering (packaging quantity doesn't matter. Ex. consider "GET SLIM JUICE 1 L" and "GET SLIM JUICE 500 ML" as one product)
product_list = pd.DataFrame(df["base_product_name"].unique())
product_list

                                  0
0                ALOE + AMLA JUICE
1            ALOE + GARCINIA JUICE
2                  ALOE VERA JUICE
3               ALOE VERA SKIN GEL
4                       NEEM JUICE
5                       NONI JUICE
6           SLIM SHAKE - CHOCOLATE
7               SLIM SHAKE - MANGO
8                   TRIPHALA JUICE
9                TULSI GILOY JUICE
10               WHEAT GRASS JUICE
11                      AMLA JUICE
12                  GET SLIM JUICE
13                    HIMALAYA OIL
14                 VIGOR MAX JUICE
15          ORGANIC JAGGERY POWDER
16              APPLE CIDER VINEGAR
17              VIRGIN COCONUT OIL
18              KARELA JAMUN JUICE
19    MASALA SUPERGRAIN MIX ENERGY
20  MASALA SUPERGRAIN MIX IMMUNITY
21              AMLA + GILOY JUICE
22                  DIA FREE JUICE
23               IMMUNE CARE JUICE
24                 ORGANIC GULKAND
25       VEGAN PROTEIN - CHOCOLATE
26               GET SLIM CAPSULES
27              RAW HONEY ( MADHU)

In [ ]:
#Question 7). Create a single excel file to save all the outputs generated above in different subsheets. Email final output file and your python code (.ipynb) file to ranotiyahemant@gmail.com
writer = pd.ExcelWriter("FMCG_summary_file.xlsx")

df_month.to_excel(writer,sheet_name="output1",index=False)
df_Category.to_excel(writer,sheet_name="output2",index=False)
df_sub_chan.to_excel(writer,sheet_name="output3",index=False)
highest_sales.to_excel(writer,sheet_name="output4",index=False)
most_selling.to_excel(writer,sheet_name="output5",index=False)
product_list.to_excel(writer,sheet_name="output6",index=False)

writer.save()